jaxon:
  core:
    debug:
      on:                          false
    prefix:
      class:                       "Jaxon"
    request:
      uri:                         "ajax.php"
      csrf_meta:                   "csrf-token"

  js:
    lib:
      uri:                         "/js"

  dialogs:
    default:
      modal:                       bootbox
      alert:                       noty
      confirm:                     noty
    pgwjs:
      assets:
        include:                   true
      modal:
        options:
          closeOnEscape:           true
          closeOnBackgroundClick:  true
          maxWidth:                600
